language : java
script : "mvn -f MebisRestServisFinal/pom.xml clean install test"
jdk: 
   - openjdk8
   - openjdk9
   - openjdk10
   - openjdk11
after_success:
   - bash <(curl -s https://codecov.io/bash)
   - 02d79518-6544-4264-9683-f770d32959b4
